@echo off
echo Starting Backend with AI Chatbot (Llama 3.1)...
cmd /k "cd /d C:/Users/ADMIN/Downloads/project/project/backend && venv311\Scripts\activate.bat && python main.py"
echo Starting Frontend...
start "Frontend" powershell -NoExit -ExecutionPolicy Bypass -Command "cd 'C:/Users/ADMIN/Downloads/project/project/frontend'; npm install; npm start"
echo Servers starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to close...
pause >nul
